-- 📁 supabase/schema.sql

-- 1. Création de la table
-- Version simplifiée sans conversion
create table documents (
    id text primary key,
    content text not null,  -- Directement en text
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

-- 2. Ajout d'un trigger pour mettre à jour updated_at automatiquement
create or replace function update_updated_at_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

create trigger update_documents_updated_at
before update on documents
for each row
execute function update_updated_at_column();

-- 3. Activation RLS
alter table documents enable row level security;

-- 4. Politiques de sécurité (ANON = public)
-- Pour utilisateurs authentifiés uniquement
-- create policy "allow auth users select documents"
-- on public.documents
-- as permissive
-- for select
-- to authenticated  -- au lieu de "anon"
-- using (true);

create policy "allow anon insert documents"
on public.documents
as permissive
for insert
to anon
with check (true);

create policy "allow anon update documents"
on public.documents
as permissive
for update
to anon
using (true)
with check (true);

create policy "allow anon select documents"
on public.documents
as permissive
for select
to anon
using (true);
create table public.document_versions (
    id bigint generated by default as identity primary key,

    document_id text not null
        references public.documents(id)
        on delete cascade,

    content text not null,

    created_at timestamptz not null default now()
);

create policy "allow anon insert document_versions"
on public.document_versions
as permissive
for insert
to anon
with check (true);

create policy "allow anon update document_versions"
on public.document_versions
as permissive
for update
to anon
using (true)
with check (true);

create policy "allow anon select document_versions"
on public.document_versions
as permissive
for select
to anon
using (true);


GRANT SELECT, INSERT, UPDATE
ON public.documents
TO anon;


GRANT SELECT, INSERT, UPDATE
ON public.document_versions
TO anon;


--- 5. trigger pour créer une version à chaque mise à jour d'un document
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger documents_set_updated_at
before update on documents
for each row
execute function set_updated_at();

-- 6. alter table pour ajouter un titre
ALTER TABLE public.documents
  ADD COLUMN title text;

-- Soft delete pour les documents (corbeille)
-- À exécuter dans l'éditeur SQL de Supabase, ou via la CLI Supabase
-- (supabase db push) si tu gères tes migrations en fichiers versionnés.

alter table public.documents
  add column deleted_at timestamp with time zone null;

-- Nécessaire pour permanentlyDelete() et emptyTrash() : sans le cascade,
-- Postgres refuse de supprimer un document tant que des lignes
-- document_versions le référencent encore.
alter table public.document_versions
  drop constraint document_versions_document_id_fkey,
  add constraint document_versions_document_id_fkey
    foreign key (document_id) references public.documents(id)
    on delete cascade;

-- Garde list() / list(true) rapides une fois la table plus grande.
create index idx_documents_deleted_at
  on public.documents (deleted_at);


alter table public.documents disable row level security;
alter table public.document_versions disable row level security;